micronaut:
  application:
    name: pdf
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/rimfirededb
    driverClassName: org.postgresql.Driver
    username: rimfirededb
    password: magical_password
    schema-generate: none
    dialect: POSTGRES
